{{- if .Values.postgres.backup.enabled -}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "kedeng.fullname" . }}-db-backups-storage
  labels:
    {{- include "kedeng.labels" . | nindent 4 }}

data:
  accessKeyId: {{ .Values.postgres.backup.storageConfig.s3Credentials.accessKeyId | b64enc | quote }}
  secretAccessKey: {{ .Values.postgres.backup.storageConfig.s3Credentials.secretAccessKey | b64enc | quote }}
{{- end -}}