{{- if .Values.postgres.pooler.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "kedeng.fullname" . }}-db-pooler-rw
  labels:
    {{- include "kedeng.labels" . | nindent 4 }}

spec:
  cluster:
    name: {{ include "kedeng.fullname" . }}-db

  instances: {{ .Values.postgres.pooler.replicas }}
  type: rw

  monitoring:
    enablePodMonitor: true

  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
{{- end -}}