apiVersion: v2
name: kedeng

type: application
version: 0.1.0

dependencies:
  - name: nats
    condition: nats.enabled
    repository: https://nats-io.github.io/k8s/helm/charts/
    version: "~1.3.7"
