---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "kedeng.fullname" . }}-influxdb-config
  labels:
    {{- include "kedeng.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb

data:
  admin-user: {{ .Values.influxdb.adminUser }}
  org: {{ .Values.influxdb.org }}
  bucket: {{ .Values.influxdb.bucket }}