{{- if .Values.influxdb.enabled -}}
{{- $name := printf "%s-influxdb-auth" (include "kedeng.fullname" .) -}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ $name }}
  labels:
    {{- include "kedeng.labels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb

data:
  {{- $previous := lookup "v1" "Secret" .Release.Namespace $name -}}  

  {{- if $previous }}
  admin-token: {{ index $previous.data "admin-token" }}
  {{- else if .Values.influxdb.adminToken }}
  admin-token: {{ .Values.influxdb.adminToken  | b64enc | quote }}
  {{- else }}
  admin-token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  {{- if $previous }}
  admin-password: {{ index $previous.data "admin-password" }}
  {{- else if .Values.influxdb.adminPassword }}
  admin-password: {{ .Values.influxdb.adminPassword  | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end -}}