{{- if .Values.data_importer.enabled -}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "kedeng.fullname" . }}-ns-api
  labels:
    {{- include "kedeng.labels" . | nindent 4 }}

data:
  apiToken: {{ .Values.global.nsApiKey | b64enc | quote }}
{{- end -}}