{{- if .Values.api.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "kedeng.fullname" . }}-api
  labels:
    {{- include "kedeng.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  rules:
    - host: {{ .Values.api.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "kedeng.fullname" . }}-api
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.api.ingress.host }}
      secretName: {{ include "kedeng.fullname" . }}-api-ingress-cert
{{- end -}}