[package]
name = "receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
async-nats = "0.39.0"
atty = "0.2.14"
bytes = "1.10.0"
flate2 = "1.1.0"
opentelemetry = "0.29.1"
opentelemetry-otlp = { version = "0.29.0", features = ["grpc-tonic"] }
opentelemetry-semantic-conventions = "0.29.0"
opentelemetry_sdk = { version = "0.29.0" , features = ["experimental_async_runtime", "rt-tokio", "experimental_metrics_periodicreader_with_async_runtime"] }
slog = "2.7.0"
slog-async = "2.8.0"
slog-json = "2.6.1"
slog-term = "2.9.1"
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["rt"] }
zeromq = "0.4.1"
