[package]
name = "receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.39.0"
atty = "0.2.14"
bytes = "1.10.0"
flate2 = "1.1.0"
slog = "2.7.0"
slog-async = "2.8.0"
slog-json = "2.6.1"
slog-term = "2.9.1"
tokio = { version = "1.43.0", features = ["full"] }
zeromq = "0.4.1"
