[package]
name = "zmq-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytes = "1.10.1"
clap = { version = "4.5.51", features = ["derive", "env"] }
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
flate2 = "1.1.5"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
slog = "2.8.2"
slog-async = "2.8.0"
slog-term = "2.9.2"
syntect = "5.3.0"
tokio = "1.48.0"
tokio-util = { version = "0.7.16", features = ["rt"] }
xml-rs = "1.0.0"
zeromq = "0.4.1"
futures-util = "0.3.31"
chrono = "0.4.42"
syntect-tui = "3.0.6"
